### ISSUE TITLE
TODO (Nilo et Gen)

### ISSUE THREAD

**Issue by nilovna** [GitMyCode/Minesweeper-AI#7]
- [ ] Faire une version exécutable du jeu et la placer dans le repo github
- [x] Embellir l’interface
- [x] Modifier les labels pour qu’ils soient tous en français
- [x] Entêtes dans les fichiers avec les noms et codes à tout le monde
- [x] Changer la classe qui s’appelle CASE vu que c’est un mot réservé
- [x] Créer un template pour la présentation (impress.js ou prezi? j’ai créé un compte étudiant sur prezi)
- [x] Déterminer quels tests nous allons passer:
  - [x] comparaison entre algos
  - [x] comparaison entre raisonnement humain et (meilleur?) algo
  - [x] limite entre CSP et probabiliste (à quel moment ça fait vraiment une différence?)
- [ ] Écrire un programme pour automatiser les tests
- [x] Cleaner le code (en particulier l’AI CSP et les noms des variables en franglais dans les autres classes)
- [x] Enlever fichiers inutiles qui sont untitled
- [x] Faire un fichier lisez-moi.txt : Un bref fichier texte ou PDF qui :
  - [x] liste vos noms, courriels et matricules;
  - [x] explique comment compiler et exécuter votre projet;
  - [x] liste et référence tous les morceaux code provenant de tierces parties.
- [ ] Faire un rapport pdf: Un fichier PDF d'un maximum de 4 pages (excluant page de présentation) résumant votre projet. Le rapport doit compléter votre présentation afin de faciliter l'évaluation du projet. Le rapport doit contenir une brève section «Répartition des tâches», d'un maximum d'une demie-page, résumant qui a fait quoi.
- [ ] Préparer la présentation: Votre présentation en format PowerPoint ou OpenOffice. Si vous utilisez un autre format, assurez-vous de l'exporter dans un format facile à consulter (PDF ou HTML). Remettez aussi les sources.
- [x] Déterminer qui sera dans la présentation, et quand est-ce qu’on la fait
- [x] Rappeler aux autres de mettre les références aux autres codes dans le lisez-moi.txt
- [x] Demander aux autres quels sont les algos qu'ils comptent implémenter
- [x] Faire un calendrier commun pour l'atteinte de nos objectifs

**Comment by GitMyCode** [comment]
Ho damm Wow. C'est excellent
